### ISSUE TITLE
Can't install HEAD on Windows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [demntor/pymodbus#14]
```
I tried to install HEAD version on Windows but I'm getting this error:

D:\escr\pymodbus>c:\Python25\python.exe setup.py install
running install
running bdist_egg
running egg_info
writing requirements to pymodbus.egg-info\requires.txt
writing pymodbus.egg-info\PKG-INFO
writing top-level names to pymodbus.egg-info\top_level.txt
writing dependency_links to pymodbus.egg-info\dependency_links.txt
Traceback (most recent call last):
  File "setup.py", line 95, in <module>
    cmdclass = command_classes,
  File "c:\Python25\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "c:\Python25\lib\distutils\dist.py", line 974, in run_commands
    self.run_command(cmd)
  File "c:\Python25\lib\distutils\dist.py", line 994, in run_command
    cmd_obj.run()
  File
"c:\Python25\lib\site-packages\setuptools-0.6c7-py2.5.egg\setuptools\comm
and\install.py", line 76, in run
  File
"c:\Python25\lib\site-packages\setuptools-0.6c7-py2.5.egg\setuptools\comm
and\install.py", line 92, in do_egg_install
  File "c:\Python25\lib\distutils\cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "c:\Python25\lib\distutils\dist.py", line 994, in run_command
    cmd_obj.run()
  File
"c:\Python25\lib\site-packages\setuptools-0.6c7-py2.5.egg\setuptools\comm
and\bdist_egg.py", line 167, in run
  File "c:\Python25\lib\distutils\cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "c:\Python25\lib\distutils\dist.py", line 994, in run_command
    cmd_obj.run()
  File
"c:\Python25\lib\site-packages\setuptools-0.6c7-py2.5.egg\setuptools\comm
and\egg_info.py", line 171, in run
  File
"c:\Python25\lib\site-packages\setuptools-0.6c7-py2.5.egg\setuptools\comm
and\egg_info.py", line 252, in find_sources
  File
"c:\Python25\lib\site-packages\setuptools-0.6c7-py2.5.egg\setuptools\comm
and\egg_info.py", line 306, in run
  File
"c:\Python25\lib\site-packages\setuptools-0.6c7-py2.5.egg\setuptools\comm
and\egg_info.py", line 333, in add_defaults
  File
"c:\Python25\lib\site-packages\setuptools-0.6c7-py2.5.egg\setuptools\comm
and\sdist.py", line 45, in walk_revctrl
  File
"c:\Python25\lib\site-packages\setuptools-0.6c7-py2.5.egg\setuptools\comm
and\sdist.py", line 52, in _default_revctrl
  File
"c:\Python25\lib\site-packages\setuptools-0.6c7-py2.5.egg\setuptools\comm
and\sdist.py", line 98, in entries_finder
NameError: global name 'log' is not defined

```

Original issue reported on code.google.com by `jjconti@gmail.com` on 3 May 2010 at 7:44

**Comment by GoogleCodeExporter** [comment]
```
This looks like it may be an issue with the version of setuptools you have 
installed.
 Can you get any more information?  I will try and find a windows box to try and
install this on.
```

Original comment by `Bashw...@gmail.com` on 7 May 2010 at 1:36

**Comment by GoogleCodeExporter** [comment]
```
Yeah, this is caused by an old version of setuptools: http://www.eby-
sarna.com/pipermail/peak/2008-April/002937.html. It should be fixed in the 
latest 
development version of setup tools.  Otherwise, here is the fix:

http://mail.python.org/pipermail/distutils-sig/2008-February/008785.html
```

Original comment by `Bashw...@gmail.com` on 16 May 2010 at 12:50
- Changed state: **WontFix**
