### ISSUE TITLE
Random error on HEAD Linux instalation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [demntor/pymodbus#17]
```
On Ubuntu, I randomly get this error when installing pymodbus. I usually
try again and the error goes away and installation process successfully
complete.


juanjo@fenix:~/python/pymodbus-svn$ sudo python setup.py install
[sudo] password for juanjo: 
running install
running bdist_egg
running egg_info
writing requirements to pymodbus.egg-info/requires.txt
writing pymodbus.egg-info/PKG-INFO
writing top-level names to pymodbus.egg-info/top_level.txt
writing dependency_links to pymodbus.egg-info/dependency_links.txt
writing manifest file 'pymodbus.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-i686/egg
running install_lib
running build_py
copying pymodbus/datastore.py -> build/lib.linux-i686-2.6/pymodbus
copying pymodbus/server/async.py -> build/lib.linux-i686-2.6/pymodbus/server
creating build/bdist.linux-i686/egg
creating build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/constants.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/pdu.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/diag_message.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/file_message.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/datastore.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/interfaces.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/version.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/utilities.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/__init__.py ->
build/bdist.linux-i686/egg/pymodbus
creating build/bdist.linux-i686/egg/pymodbus/client
copying build/lib.linux-i686-2.6/pymodbus/client/sync.py ->
build/bdist.linux-i686/egg/pymodbus/client
copying build/lib.linux-i686-2.6/pymodbus/client/__init__.py ->
build/bdist.linux-i686/egg/pymodbus/client
copying build/lib.linux-i686-2.6/pymodbus/client/async.py ->
build/bdist.linux-i686/egg/pymodbus/client
copying build/lib.linux-i686-2.6/pymodbus/factory.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/register_write_message.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/bit_read_message.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/transaction.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/other_message.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/register_read_message.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/device.py ->
build/bdist.linux-i686/egg/pymodbus
copying build/lib.linux-i686-2.6/pymodbus/bit_write_message.py ->
build/bdist.linux-i686/egg/pymodbus
creating build/bdist.linux-i686/egg/pymodbus/server
copying build/lib.linux-i686-2.6/pymodbus/server/sync.py ->
build/bdist.linux-i686/egg/pymodbus/server
copying build/lib.linux-i686-2.6/pymodbus/server/__init__.py ->
build/bdist.linux-i686/egg/pymodbus/server
copying build/lib.linux-i686-2.6/pymodbus/server/async.py ->
build/bdist.linux-i686/egg/pymodbus/server
copying build/lib.linux-i686-2.6/pymodbus/mexceptions.py ->
build/bdist.linux-i686/egg/pymodbus
creating build/bdist.linux-i686/egg/test
copying build/lib.linux-i686-2.6/test/test_factory.py ->
build/bdist.linux-i686/egg/test
copying build/lib.linux-i686-2.6/test/test_datastore.py ->
build/bdist.linux-i686/egg/test
copying build/lib.linux-i686-2.6/test/test_diag_messages.py ->
build/bdist.linux-i686/egg/test
copying build/lib.linux-i686-2.6/test/test_pdu.py ->
build/bdist.linux-i686/egg/test
copying build/lib.linux-i686-2.6/test/test_transaction.py ->
build/bdist.linux-i686/egg/test
copying build/lib.linux-i686-2.6/test/test_utilities.py ->
build/bdist.linux-i686/egg/test
copying build/lib.linux-i686-2.6/test/__init__.py ->
build/bdist.linux-i686/egg/test
copying build/lib.linux-i686-2.6/test/test_mexceptions.py ->
build/bdist.linux-i686/egg/test
copying build/lib.linux-i686-2.6/test/test_register_messages.py ->
build/bdist.linux-i686/egg/test
copying build/lib.linux-i686-2.6/test/test_device.py ->
build/bdist.linux-i686/egg/test
copying build/lib.linux-i686-2.6/test/test_client.py ->
build/bdist.linux-i686/egg/test
copying build/lib.linux-i686-2.6/test/test_bit_messages.py ->
build/bdist.linux-i686/egg/test
byte-compiling build/bdist.linux-i686/egg/pymodbus/constants.py to
constants.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/pdu.py to pdu.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/diag_message.py to
diag_message.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/file_message.py to
file_message.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/datastore.py to
datastore.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/interfaces.py to
interfaces.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/version.py to version.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/utilities.py to
utilities.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/client/sync.py to sync.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/client/__init__.py to
__init__.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/client/async.py to async.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/factory.py to factory.pyc
byte-compiling
build/bdist.linux-i686/egg/pymodbus/register_write_message.py to
register_write_message.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/bit_read_message.py to
bit_read_message.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/transaction.py to
transaction.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/other_message.py to
other_message.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/register_read_message.py
to register_read_message.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/device.py to device.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/bit_write_message.py to
bit_write_message.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/server/sync.py to sync.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/server/__init__.py to
__init__.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/server/async.py to async.pyc
byte-compiling build/bdist.linux-i686/egg/pymodbus/mexceptions.py to
mexceptions.pyc
byte-compiling build/bdist.linux-i686/egg/test/test_factory.py to
test_factory.pyc
byte-compiling build/bdist.linux-i686/egg/test/test_datastore.py to
test_datastore.pyc
byte-compiling build/bdist.linux-i686/egg/test/test_diag_messages.py to
test_diag_messages.pyc
byte-compiling build/bdist.linux-i686/egg/test/test_pdu.py to test_pdu.pyc
byte-compiling build/bdist.linux-i686/egg/test/test_transaction.py to
test_transaction.pyc
byte-compiling build/bdist.linux-i686/egg/test/test_utilities.py to
test_utilities.pyc
byte-compiling build/bdist.linux-i686/egg/test/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/test/test_mexceptions.py to
test_mexceptions.pyc
byte-compiling build/bdist.linux-i686/egg/test/test_register_messages.py to
test_register_messages.pyc
byte-compiling build/bdist.linux-i686/egg/test/test_device.py to
test_device.pyc
byte-compiling build/bdist.linux-i686/egg/test/test_client.py to
test_client.pyc
byte-compiling build/bdist.linux-i686/egg/test/test_bit_messages.py to
test_bit_messages.pyc
creating build/bdist.linux-i686/egg/EGG-INFO
copying pymodbus.egg-info/PKG-INFO -> build/bdist.linux-i686/egg/EGG-INFO
copying pymodbus.egg-info/SOURCES.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying pymodbus.egg-info/dependency_links.txt ->
build/bdist.linux-i686/egg/EGG-INFO
copying pymodbus.egg-info/requires.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying pymodbus.egg-info/top_level.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying pymodbus.egg-info/zip-safe -> build/bdist.linux-i686/egg/EGG-INFO
creating 'dist/pymodbus-0.5.1-py2.6.egg' and adding
'build/bdist.linux-i686/egg' to it
removing 'build/bdist.linux-i686/egg' (and everything under it)
Processing pymodbus-0.5.1-py2.6.egg
Removing /usr/local/lib/python2.6/dist-packages/pymodbus-0.5.1-py2.6.egg
Copying pymodbus-0.5.1-py2.6.egg to /usr/local/lib/python2.6/dist-packages
pymodbus 0.5.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.6/dist-packages/pymodbus-0.5.1-py2.6.egg
Processing dependencies for pymodbus==0.5.1
Traceback (most recent call last):
  File "setup.py", line 95, in <module>
    cmdclass = command_classes,
  File "/usr/lib/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/dist-packages/setuptools/command/install.py",
line 76, in run
    self.do_egg_install()
  File "/usr/lib/python2.6/dist-packages/setuptools/command/install.py",
line 104, in do_egg_install
    cmd.run()
  File
"/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line
229, in run
    self.easy_install(spec, not self.no_deps)
  File
"/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line
445, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File
"/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line
496, in install_item
    self.process_distribution(spec, dist, deps)
  File
"/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line
537, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 529, in
resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 2108, in
requires
    dm = self._dep_map
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 2100, in
_dep_map
    for extra,reqs in split_sections(self._get_metadata(name)):
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 2519, in
split_sections
    for line in yield_lines(s):
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1813, in
yield_lines
    for ss in strs:
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 2122, in
_get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1140, in
get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1137, in
get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1197, in _get
    return self.loader.get_data(path)
zipimport.ZipImportError: bad local file header in
/usr/local/lib/python2.6/dist-packages/pymodbus-0.5.1-py2.6.egg

```

Original issue reported on code.google.com by `jjconti@gmail.com` on 11 May 2010 at 2:01

**Comment by GoogleCodeExporter** [comment]
```
I haven't seen this, but according to the following post it appears to be an 
issue with 
the zipimport's caching: http://mail.python.org/pipermail/distutils-sig/2009-
February/010971.html.

I'll leave this open for now for tracking.
```

Original comment by `Bashw...@gmail.com` on 15 May 2010 at 10:17

**Comment by GoogleCodeExporter** [comment]
```
I haven't heard about this in a while.
```

Original comment by `Bashw...@gmail.com` on 5 Jan 2011 at 7:31
- Changed state: **WontFix**
