### ISSUE TITLE
Cant read RTU data

### ISSUE THREAD

**Issue by GoogleCodeExporter** [demntor/pymodbus#59]
```
What steps will reproduce the problem?
1. Connecting to an RTU serial client
2. Try to read from a holding register


I keep getting a recurring issue where python yells at me with the following: 

"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.cygwin-1.7.11-i686/egg/pymodbus/client/common.py", line 109, in read_holding_registers
  File "build/bdist.cygwin-1.7.11-i686/egg/pymodbus/client/sync.py", line 131, in execute
  File "build/bdist.cygwin-1.7.11-i686/egg/pymodbus/client/sync.py", line 51, in execute
  File "build/bdist.cygwin-1.7.11-i686/egg/pymodbus/transaction.py", line 406, in processIncomingPacket
  File "build/bdist.cygwin-1.7.11-i686/egg/pymodbus/transaction.py", line 310, in checkFrame
  File "build/bdist.cygwin-1.7.11-i686/egg/pymodbus/transaction.py", line 352, in populateHeader
AttributeError: 'NoneType' object has no attribute 'calculateRtuFrameSize'
"

```

Original issue reported on code.google.com by `TextTedX...@gmail.com` on 26 Mar 2012 at 8:48

**Comment by GoogleCodeExporter** [comment]
```
This should be fixed in the current version (in the git repository on github).  
There was an error with exception responses not being properly sent down the 
chain (with None's instead).  Let me know if the problem still persists.
```

Original comment by `Bashw...@gmail.com` on 6 Jun 2012 at 6:37
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `Bashw...@gmail.com` on 8 Jun 2012 at 1:53
- Changed state: **Fixed**
