### ISSUE TITLE
Install fail on cygwin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [demntor/pymodbus#64]
```
I tried installing first by downloading the pymodbus-0.9.0.zip and running 
python setup.py install in the pymodbus-0.9.0 directory:

$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    from ez_setup import use_setuptools
ImportError: No module named ez_setup

Then I followed the instructions and did:

$ svn checkout http://pymodbus.googlecode.com/svn/trunk/ pymodbus-read-only
<lots of stuff>
$ cd pymodbus-read-only/
$ python setup.py install

---------------------------------------------------------------------------
This script requires setuptools version 0.6c9 to run (even to display
help).  I will attempt to download it for you (from
http://pypi.python.org/packages/2.6/s/setuptools/), but
you may need to enable firewall access for this script first.
I will start the download in 15 seconds.

(Note: if this machine does not have network access, please obtain the file

   http://pypi.python.org/packages/2.6/s/setuptools/setuptools-0.6c9-py2.6.egg

and place it in this directory before rerunning this script.)
---------------------------------------------------------------------------
Downloading 
http://pypi.python.org/packages/2.6/s/setuptools/setuptools-0.6c9-py2.6.egg
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    setup(name  = 'pymodbus',
NameError: name 'setup' is not defined

I tried to re-run the install and got the same traceback.

```

Original issue reported on code.google.com by `sea...@gmail.com` on 25 Sep 2012 at 4:44

**Comment by GoogleCodeExporter** [comment]
```
Can you please try again with the version from github?  The code on google's 
site isn't being maintained anymore.
```

Original comment by `Bashw...@gmail.com` on 17 Dec 2012 at 3:09

**Comment by GoogleCodeExporter** [comment]
Original comment by `Bashw...@gmail.com` on 13 Jan 2013 at 7:30
- Changed state: **Invalid**
